name: Python test workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  pytest:
    runs-on: ubuntu-latest
    name: Test python
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.1

      - name: Install poetry
        run: |
          python -m pip install poetry==1.3.2

      - name: Configure poetry
        run: |
          python -m poetry config virtualenvs.in-project true

      - name: Cache the virtualenv
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: |
          python -m poetry install

      - name: pytest testing
        run: |
          poetry run pytest
        
      - name: pytest coverage
        run:
          poetry run pytest --cov=./ --cov-report=xml:tests/coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      #- name: Run tests
      #  run: |
      #    python -m poetry run python -m pytest -sxv
